Pod::Spec.new do |s|
  s.name         = "bingle_jsi"
  s.version      = "0.0.1"
  s.summary      = "React Native native module for Bingle P2P messaging (iOS)"
  s.description  = "Provides the Bingle JSI API to React Native iOS apps via uniffi-generated Swift bindings and a pre-built XCFramework."
  s.homepage     = "https://github.com/example/bingle_jsi"
  s.license      = "UNLICENSED"
  s.author       = "Bingle"
  s.platform     = :ios, "13.0"
  s.source       = { :path => "." }

  # Swift bindings generated by uniffi-bindgen (build_ios.sh)
  s.source_files = "ios/generated/**/*.swift"

  # Pre-built XCFramework containing the Rust static library
  s.vendored_frameworks = "ios/BingleJsi.xcframework"

  # Preserve the generated C headers and modulemap inside the framework
  s.preserve_paths = "ios/generated/**/*"

  # The Rust library depends on system frameworks
  s.frameworks = "Foundation", "Security"
  s.libraries  = "c++", "resolv"

  s.swift_version = "5.7"
  s.static_framework = true
end
