Pod::Spec.new do |s|
  s.name         = "bingle_jsi"
  s.version      = "0.0.1"
  s.summary      = "React Native native module for Bingle P2P messaging (iOS)"
  s.description  = "Provides the Bingle JSI API to React Native iOS apps via uniffi-generated Swift bindings and a pre-built XCFramework."
  s.homepage     = "https://github.com/example/bingle_jsi"
  s.license      = "UNLICENSED"
  s.author       = "Bingle"
  s.platform     = :ios, "13.0"
  s.source       = { :path => "." }

  # Swift bindings generated by uniffi-bindgen (build_ios.sh)
  # plus the React Native bridge files
  s.source_files = "ios/generated/**/*.swift", "ios/BingleJsiBridge.swift", "ios/BingleJsiBridge.m"

  # Pre-built XCFramework containing the Rust static library
  s.vendored_frameworks = "ios/BingleJsi.xcframework"

  # Preserve the generated C headers and modulemap inside the framework
  s.preserve_paths = "ios/generated/**/*"

  # The Rust library depends on system frameworks
  s.frameworks = "Foundation", "Security"
  s.libraries  = "c++", "resolv"

  s.swift_version = "5.7"
  s.static_framework = true

  # The Rust static library inside the XCFramework has the same name
  # (libbingle_jsi.a) as the pod's own compiled Swift archive. Without
  # force_load the linker only picks up the Swift object code and misses
  # the Rust FFI symbols. This flag ensures the Rust library is linked
  # into the final app binary.
  s.xcconfig = {
    'OTHER_LDFLAGS' => '$(inherited) -force_load "${PODS_XCFRAMEWORKS_BUILD_DIR}/bingle_jsi/libbingle_jsi.a"'
  }

  s.dependency "React-Core"
end
