#!/usr/bin/env bash

CREATOR_PASSPHRASE="version rural bring cushion ball case borrow present avoid else pupil alcohol marine attitude extra favorite mass move midnight symbol sibling latin language able borrow"

# Ensure cleanup of background containers on exit
cleanup() {
  docker stop bingle_relay_a bingle_relay_b bingle_stun_a bingle_stun_b bingle_pingable >/dev/null 2>&1 || true
}
trap cleanup EXIT

# Relay20 on 127.0.0.1:20020
RELAY_A_HANDLE=relay20
RELAY_A_ADDRESS=J3GHIF4QBJT7PEQHJ7YNJXP64RY7Q27GRB6HEFJ7O5E6JULGNSPVP546N4
RELAY_A_PASSPHRASE="parent diamond bring another suggest rice diamond gravity bench violin hover fat relax annual repeat keen use moon senior display laundry asthma trend absorb grab"
RELAY_A_PORT=20020

# Relay21 on 127.0.0.1:20021
RELAY_B_HANDLE=relay21
RELAY_B_ADDRESS=ZEBF7TPP3ZKVPBUSXDRZE2XIRLBRBYFQF6PFEXXLTFMOP6ETX3HFKG7D6Y
RELAY_B_PASSPHRASE="design coast gift sting park tooth comic load off feed super close civil divide orbit garden mutual boat wine analyst gospel stem pipe about ritual"
RELAY_B_PORT=20021

TESTNET_USER=testuser10
TESTNET_ADDRESS=SRIDWL763LIECMBL5N4WRJE6TGBBJL6SKJ6OZOMEQSGAOKW5JEBVUUH3QU
TESTNET_PASSPHRASE="sand fantasy youth fix suggest immense stem awful piano pyramid garment wear butter setup cake finger hawk game language demise company surprise rule about during"

PINGABLE_USER=pinguser20
PINGABLE_ADDRESS=SRIDF3MQNHGWOKYNZOSS7VONPKJB2LM52DOZGPY7QLT5ONZ5BPUAKH3Q4A
PINGABLE_PASSPHRASE="sudden defy hunt quick lens long slender pupil example affair select announce flower meadow refuse owner beauty write always scene kiss cage picture ability gorilla"

# Update these users
bingle_admin root $RELAY_A_ADDRESS --enable \
 --node-file nodely_testnet_node.json \
 --passphrase "$CREATOR_PASSPHRASE"

bingle_admin root $RELAY_B_ADDRESS --enable \
 --node-file nodely_testnet_node.json \
 --passphrase "$CREATOR_PASSPHRASE"

bingle_admin updateuser --handle $TESTNET_USER \
 --passphrase "$CREATOR_PASSPHRASE" \
 --node-file nodely_testnet_node.json \
 --userpassphrase "$TESTNET_PASSPHRASE"

bingle_admin updateuser --handle $PINGABLE_USER \
 --passphrase "$CREATOR_PASSPHRASE" \
 --node-file nodely_testnet_node.json \
 --userpassphrase "$PINGABLE_PASSPHRASE"

# Ensure a dedicated test network exists
if ! docker network inspect bingle_testnet >/dev/null 2>&1; then
  docker network create bingle_testnet >/dev/null
fi

# Start two local STUN servers in Docker (coturn in STUN-only mode)
docker rm -f bingle_stun_a bingle_stun_b >/dev/null 2>&1 || true

docker run --rm -d \
  --name bingle_stun_a \
  --network bingle_testnet \
  instrumentisto/coturn \
  turnserver -n --no-tls --no-dtls --listening-port 3478 --fingerprint --lt-cred-mech=0 --max-bps=0 --min-port=49152 --max-port=49200

docker run --rm -d \
  --name bingle_stun_b \
  --network bingle_testnet \
  instrumentisto/coturn \
  turnserver -n --no-tls --no-dtls --listening-port 3478 --fingerprint --lt-cred-mech=0 --max-bps=0 --min-port=49152 --max-port=49200

# Fetch the internal Docker IPs of the STUN servers
STUN_A_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' bingle_stun_a)
STUN_B_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' bingle_stun_b)
if [[ -z "$STUN_A_IP" || -z "$STUN_B_IP" ]]; then
  echo "Failed to discover STUN container IPs" >&2
  exit 2
fi

# Prepare a stunservers.txt that references the containers by their internal Docker IPs
mkdir -p tmp
cat > tmp/stunservers.txt <<EOF
# Auto-generated by run_testnet_tests.sh
${STUN_A_IP}:3478
${STUN_B_IP}:3478
EOF

echo "Using STUN servers: ${STUN_A_IP}:3478, ${STUN_B_IP}:3478"

# Start relay containers on the same docker network
# They will autodetect EXTERNAL_IP inside the container and register static endpoints
# reachable from other containers on this network.
docker run --platform linux/arm64 --rm -d \
 --name bingle_relay_a \
 --network bingle_testnet \
 -e RELAY=1 \
 -e PASSPHRASE="$RELAY_A_PASSPHRASE" \
 -e PORT=$RELAY_A_PORT \
 -e HANDLE=$RELAY_A_HANDLE \
 "bingle:local"
sleep 20

docker run --platform linux/arm64 --rm -d \
 --name bingle_relay_b \
 --network bingle_testnet \
 -e RELAY=1 \
 -e PASSPHRASE="$RELAY_B_PASSPHRASE" \
 -e PORT=$RELAY_B_PORT \
 -e HANDLE=$RELAY_B_HANDLE \
 "bingle:local"
sleep 20

# Start the ping target
docker run --platform linux/arm64 -d --rm \
 --name bingle_pingable \
 --network bingle_testnet \
 -e PASSPHRASE="$PINGABLE_PASSPHRASE" \
 -e PORT=30001 \
 -e HANDLE=$PINGABLE_USER \
 -v "$PWD/tmp/stunservers.txt":/app/stunservers.txt:ro \
 "bingle:local"
sleep 20

# Build or refresh the tests image (uses Dockerfile tests stage and prebuilt test binary)
export BINGLE_RUN_TESTNET=1
export TESTNET_USER=$TESTNET_USER
export TESTNET_PASSPHRASE="$TESTNET_PASSPHRASE"

# Ensure the latest tests image is built from the current workspace
scripts/build_tests_image.sh --tag bingle-tests:local

# Prepare output directory to collect results from the container
mkdir -p tmp/test_out

# File paths for collecting results from each docker run
MAIN_OUT="$PWD/tmp/test_out/test_results_main.out"
PING_OUT="$PWD/tmp/test_out/test_results_ping.out"

# Ensure previous outputs are cleared
: > "$MAIN_OUT"
: > "$PING_OUT"

# Run the prebuilt test inside the dedicated tests image (streams output and waits for completion)
# NAT_MODE can be set by the caller to control iptables behavior in the test container: Direct|Full|Restricted|All
# Default to All to exercise all three modes in sequence with a final summary
NAT_MODE=${NAT_MODE:-All}

docker run --platform linux/arm64 --rm \
  --name bingle_test_runner \
  --network bingle_testnet \
  --cap-add NET_ADMIN \
  -e NAT_MODE="$NAT_MODE" \
  -e TESTNET_USER="$TESTNET_USER" \
  -e TESTNET_PASSPHRASE="$TESTNET_PASSPHRASE" \
  -e OUT_FILE="/out/$(basename "$MAIN_OUT")" \
  -v "$PWD/tmp/test_out":/out \
  -v "$PWD/tmp/stunservers.txt":/app/stunservers.txt:ro \
  "bingle-tests:local"
MAIN_RC=$?

# Build image for ping_registered_node test and run it in Direct NAT mode only
scripts/build_tests_image.sh --tag bingle-tests:ping --test ping_registered_node

# Run the ping test: Direct mode only, set explicit filter to the ping test function and pass pingable address
PING_FILTER="testnet_send_ping_to_registered_node"

docker run --platform linux/arm64 --rm \
  --name bingle_test_runner_ping \
  --network bingle_testnet \
  --cap-add NET_ADMIN \
  -e NAT_MODE="Direct" \
  -e TEST_FILTER="$PING_FILTER" \
  -e TESTNET_USER="$TESTNET_USER" \
  -e TESTNET_PASSPHRASE="$TESTNET_PASSPHRASE" \
  -e PINGABLE_ADDRESS="$PINGABLE_ADDRESS" \
  -e OUT_FILE="/out/$(basename "$PING_OUT")" \
  -v "$PWD/tmp/test_out":/out \
  -v "$PWD/tmp/stunservers.txt":/app/stunservers.txt:ro \
  "bingle-tests:ping"
PING_RC=$?

# Attempt to stop the ping runner explicitly (in case it lingered)
docker stop bingle_test_runner_ping >/dev/null 2>&1 || true

# ---------------------------
# Extract and consolidate results
# ---------------------------
echo ""
echo "================ Consolidated Test Results ================"

# Show individual results from the main run
if [[ -f "$MAIN_OUT" ]]; then
  echo "-- Main run (per-mode results) --"
  grep -E '^\[runner\]\[(Direct|Full|Restricted)\] Test ' "$MAIN_OUT" || echo "(no per-mode result lines found)"
  echo "-- Main run (summary) --"
  grep -E '^\[runner\]\[summary\]' "$MAIN_OUT" || echo "(no summary lines found)"
else
  echo "[WARN] Main results file not found: $MAIN_OUT"
fi

# Show results from the ping run
if [[ -f "$PING_OUT" ]]; then
  echo "-- Ping run (per-mode results) --"
  grep -E '^\[runner\]\[(Direct|Full|Restricted)\] Test ' "$PING_OUT" || echo "(no per-mode result lines found)"
else
  echo "[WARN] Ping results file not found: $PING_OUT"
fi

# Determine statuses
MAIN_STATUS="UNKNOWN"
PING_STATUS="UNKNOWN"

if [[ -f "$MAIN_OUT" ]]; then
  if grep -Eq '^\[runner\]\[summary\].*FAILED' "$MAIN_OUT"; then
    MAIN_STATUS="FAIL"
  elif grep -Eq '^\[runner\]\[summary\].*PASSED' "$MAIN_OUT"; then
    # If any PASSED summaries found and no FAILED, consider PASS
    MAIN_STATUS="PASS"
  else
    # Fall back to exit code
    if [[ ${MAIN_RC:-1} -eq 0 ]]; then MAIN_STATUS="PASS"; else MAIN_STATUS="FAIL"; fi
  fi
else
  if [[ ${MAIN_RC:-1} -eq 0 ]]; then MAIN_STATUS="PASS"; else MAIN_STATUS="FAIL"; fi
fi

if [[ -f "$PING_OUT" ]]; then
  if grep -Eq '^\[runner\]\[Direct\] Test PASSED' "$PING_OUT"; then
    PING_STATUS="PASS"
  elif grep -Eq '^\[runner\]\[(Direct|Full|Restricted)\] Test FAILED' "$PING_OUT"; then
    PING_STATUS="FAIL"
  else
    if [[ ${PING_RC:-1} -eq 0 ]]; then PING_STATUS="PASS"; else PING_STATUS="FAIL"; fi
  fi
else
  if [[ ${PING_RC:-1} -eq 0 ]]; then PING_STATUS="PASS"; else PING_STATUS="FAIL"; fi
fi

echo "-- Overall --"
echo "Main run: $MAIN_STATUS"
echo "Ping run: $PING_STATUS"

if [[ "$MAIN_STATUS" == "PASS" && "$PING_STATUS" == "PASS" ]]; then
  echo "OVERALL RESULT: PASS"
  exit 0
else
  echo "OVERALL RESULT: FAIL"
  # Prefer returning the first non-zero original RC if available
  if [[ ${MAIN_RC:-0} -ne 0 ]]; then exit ${MAIN_RC:-1}; fi
  if [[ ${PING_RC:-0} -ne 0 ]]; then exit ${PING_RC:-1}; fi
  exit 1
fi

