#!/usr/bin/env bash

CREATOR_PASSPHRASE="version rural bring cushion ball case borrow present avoid else pupil alcohol marine attitude extra favorite mass move midnight symbol sibling latin language able borrow"

# Ensure cleanup of background containers on exit
cleanup() {
  docker stop bingle_relay_a bingle_relay_b bingle_stun_a bingle_stun_b bingle_pingable >/dev/null 2>&1 || true
}
trap cleanup EXIT

# Wait for a file to appear with timeout (seconds)
wait_for_file() {
  local file="$1"; shift
  local timeout="${1:-120}"
  local elapsed=0
  echo "Waiting for sentinel: $file (timeout ${timeout}s)"
  while [ $elapsed -lt $timeout ]; do
    if [ -f "$file" ]; then
      echo "Sentinel present: $file"
      return 0
    fi
    sleep 1
    elapsed=$((elapsed+1))
  done
  echo "ERROR: Timeout waiting for sentinel $file" >&2
  return 1
}

# Relay20 on 127.0.0.1:20020
RELAY_A_HANDLE=relay20
RELAY_A_ADDRESS=J3GHIF4QBJT7PEQHJ7YNJXP64RY7Q27GRB6HEFJ7O5E6JULGNSPVP546N4
RELAY_A_PASSPHRASE="parent diamond bring another suggest rice diamond gravity bench violin hover fat relax annual repeat keen use moon senior display laundry asthma trend absorb grab"
RELAY_A_PORT=20020

# Relay21 on 127.0.0.1:20021
RELAY_B_HANDLE=relay21
RELAY_B_ADDRESS=ZEBF7TPP3ZKVPBUSXDRZE2XIRLBRBYFQF6PFEXXLTFMOP6ETX3HFKG7D6Y
RELAY_B_PASSPHRASE="design coast gift sting park tooth comic load off feed super close civil divide orbit garden mutual boat wine analyst gospel stem pipe about ritual"
RELAY_B_PORT=20021

TESTNET_USER=testuser10
TESTNET_ADDRESS=SRIDWL763LIECMBL5N4WRJE6TGBBJL6SKJ6OZOMEQSGAOKW5JEBVUUH3QU
TESTNET_PASSPHRASE="sand fantasy youth fix suggest immense stem awful piano pyramid garment wear butter setup cake finger hawk game language demise company surprise rule about during"

PINGABLE_USER=pinguser20
PINGABLE_ADDRESS=SRIDF3MQNHGWOKYNZOSS7VONPKJB2LM52DOZGPY7QLT5ONZ5BPUAKH3Q4A
PINGABLE_PASSPHRASE="sudden defy hunt quick lens long slender pupil example affair select announce flower meadow refuse owner beauty write always scene kiss cage picture ability gorilla"
PINGABLE_PORT=30001

# NAT mode for tests. Accept Direct|Full|Restricted|All (default All)
NAT_MODE=${NAT_MODE:-All}
# Determine initial NAT mode for the pingable container
if [ "$NAT_MODE" = "All" ] || [ "$NAT_MODE" = "all" ]; then
  PING_INIT_MODE="Direct"
else
  PING_INIT_MODE="$NAT_MODE"
fi

# Update these users
bingle_admin root $RELAY_A_ADDRESS --enable \
 --node-file nodely_testnet_node.json \
 --passphrase "$CREATOR_PASSPHRASE"

bingle_admin root $RELAY_B_ADDRESS --enable \
 --node-file nodely_testnet_node.json \
 --passphrase "$CREATOR_PASSPHRASE"

bingle_admin updateuser --handle $TESTNET_USER \
 --passphrase "$CREATOR_PASSPHRASE" \
 --node-file nodely_testnet_node.json \
 --userpassphrase "$TESTNET_PASSPHRASE"

bingle_admin updateuser --handle $PINGABLE_USER \
 --passphrase "$CREATOR_PASSPHRASE" \
 --node-file nodely_testnet_node.json \
 --userpassphrase "$PINGABLE_PASSPHRASE"

# Ensure a dedicated test network exists with custom subnet for IP assignment
if ! docker network inspect bingle_testnet >/dev/null 2>&1; then
  docker network create --subnet=172.18.0.0/16 bingle_testnet >/dev/null
fi

# Start two local STUN servers in Docker (coturn in STUN-only mode)
docker rm -f bingle_stun_a bingle_stun_b >/dev/null 2>&1 || true

docker run --rm -d \
  --name bingle_stun_a \
  --network bingle_testnet \
  instrumentisto/coturn \
  turnserver -n --no-tls --no-dtls --listening-port 3478 --fingerprint --lt-cred-mech=0 --max-bps=0 --min-port=49152 --max-port=49200

if [ $? -ne 0 ]; then
    echo "ERROR: Failed to start bingle_stun_a container" >&2
    exit 1
fi

docker run --rm -d \
  --name bingle_stun_b \
  --network bingle_testnet \
  instrumentisto/coturn \
  turnserver -n --no-tls --no-dtls --listening-port 3478 --fingerprint --lt-cred-mech=0 --max-bps=0 --min-port=49152 --max-port=49200

if [ $? -ne 0 ]; then
    echo "ERROR: Failed to start bingle_stun_b container" >&2
    exit 1
fi

# Fetch the internal Docker IPs of the STUN servers
STUN_A_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' bingle_stun_a)
STUN_B_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' bingle_stun_b)
if [[ -z "$STUN_A_IP" || -z "$STUN_B_IP" ]]; then
  echo "Failed to discover STUN container IPs" >&2
  exit 2
fi

# Prepare a stunservers.txt that references the containers by their internal Docker IPs
mkdir -p tmp tmp/sentinels
cat > tmp/stunservers.txt <<EOF
# Auto-generated by run_testnet_tests.sh
${STUN_A_IP}:3478
${STUN_B_IP}:3478
EOF

echo "Using STUN servers: ${STUN_A_IP}:3478, ${STUN_B_IP}:3478"

# Sentinel directory and file names
SENT_DIR="$PWD/tmp/sentinels"
RELAY_A_SENT="relay_${RELAY_A_HANDLE}_${RELAY_A_PORT}.sentinel"
RELAY_B_SENT="relay_${RELAY_B_HANDLE}_${RELAY_B_PORT}.sentinel"

# Start relay containers on the same docker network
# They will autodetect EXTERNAL_IP inside the container and register static endpoints
# reachable from other containers on this network.
# Remove any old sentinel files
rm -f "$SENT_DIR/$RELAY_A_SENT" "$SENT_DIR/$RELAY_B_SENT"

docker run --platform linux/arm64 --rm -d \
 --name bingle_relay_a \
 --network bingle_testnet \
 -e RELAY=1 \
 -e PASSPHRASE="$RELAY_A_PASSPHRASE" \
 -e PORT=$RELAY_A_PORT \
 -e HANDLE=$RELAY_A_HANDLE \
 -e SENTINEL_FILE="/sentinels/$RELAY_A_SENT" \
 -v "$PWD/tmp/sentinels":/sentinels \
 "bingle:local"

if [ $? -ne 0 ]; then
    echo "ERROR: Failed to start bingle_relay_a container" >&2
    exit 1
fi

docker run --platform linux/arm64 -d --rm \
 --name bingle_relay_b \
 --network bingle_testnet \
 -e RELAY=1 \
 -e PASSPHRASE="$RELAY_B_PASSPHRASE" \
 -e PORT=$RELAY_B_PORT \
 -e HANDLE=$RELAY_B_HANDLE \
 -e SENTINEL_FILE="/sentinels/$RELAY_B_SENT" \
 -v "$PWD/tmp/sentinels":/sentinels \
 "bingle:local"

if [ $? -ne 0 ]; then
    echo "ERROR: Failed to start bingle_relay_b container" >&2
    exit 1
fi

# Wait for both relay sentinels before continuing
wait_for_file "$SENT_DIR/$RELAY_A_SENT" 180 || exit 1
wait_for_file "$SENT_DIR/$RELAY_B_SENT" 180 || exit 1

# Start the ping target
echo "Restarting ping target mode ${PING_INIT_MODE}"
# Initialize IP address tracking for bingle_pingable container
PINGABLE_IP_SUFFIX=100
echo "Using IP address 172.18.0.$PINGABLE_IP_SUFFIX for initial bingle_pingable"
PING_INIT_SENT="pingable_${PING_INIT_MODE}_${PINGABLE_PORT}.sentinel"
echo "Delete sentinel ${SENT_DIR}/${PING_INIT_SENT}"
rm -f "$SENT_DIR/$PING_INIT_SENT"

docker run --platform linux/arm64 -d --rm \
 --name bingle_pingable \
 --network bingle_testnet \
 --ip "172.18.0.$PINGABLE_IP_SUFFIX" \
 --cap-add NET_ADMIN \
 -e RUST_BACKTRACE=1 \
 -e EXTRA_ARGS="--log-debug" \
 -e PASSPHRASE="$PINGABLE_PASSPHRASE" \
 -e PORT=$PINGABLE_PORT \
 -e HANDLE=$PINGABLE_USER \
 -e NAT_MODE="$PING_INIT_MODE" \
 -e SENTINEL_FILE="/sentinels/$PING_INIT_SENT" \
 -v "$PWD/tmp/sentinels":/sentinels \
 -v "$PWD/tmp/stunservers.txt":/app/stunservers.txt:ro \
 "bingle:local"

if [ $? -ne 0 ]; then
    echo "ERROR: Failed to start bingle_pingable container" >&2
    exit 1
fi

# Wait for pingable listening sentinel
echo "Waiting for ${SENT_DIR}/${PING_INIT_SENT}"
wait_for_file "$SENT_DIR/$PING_INIT_SENT" 180 || exit 1
echo "Ping target restarted"

# Build or refresh the tests image (uses Dockerfile tests stage and prebuilt test binary)
export BINGLE_RUN_TESTNET=1
export TESTNET_USER=$TESTNET_USER
export TESTNET_PASSPHRASE="$TESTNET_PASSPHRASE"

# Ensure the latest tests image is built from the current workspace
scripts/build_tests_image.sh --tag bingle-tests:local

# Prepare output directory to collect results from the container
mkdir -p tmp/test_out

# File paths for collecting results from each docker run
MAIN_OUT="$PWD/tmp/test_out/test_results_main.out"
PING_OUT="$PWD/tmp/test_out/test_results_ping.out"

# Ensure previous outputs are cleared
: > "$MAIN_OUT"
: > "$PING_OUT"

# Run the prebuilt test inside the dedicated tests image (streams output and waits for completion)
# NAT_MODE can be set by the caller to control iptables behavior in the test container: Direct|Full|Restricted|All
# Default to All to exercise all three modes in sequence with a final summary
NAT_MODE=${NAT_MODE:-All}

docker run --platform linux/arm64 --rm \
  --name bingle_test_runner \
  --network bingle_testnet \
  --cap-add NET_ADMIN \
  -e NAT_MODE="$NAT_MODE" \
  -e TESTNET_USER="$TESTNET_USER" \
  -e TESTNET_PASSPHRASE="$TESTNET_PASSPHRASE" \
  -e OUT_FILE="/out/$(basename "$MAIN_OUT")" \
  -v "$PWD/tmp/test_out":/out \
  -v "$PWD/tmp/stunservers.txt":/app/stunservers.txt:ro \
  "bingle-tests:local"
MAIN_RC=$?

if [ $MAIN_RC -ne 0 ]; then
    echo "ERROR: Main test container failed with exit code $MAIN_RC" >&2
    # Don't exit here - we want to collect results and run the ping test
fi

# Build image for ping_registered_node test once
scripts/build_tests_image.sh --tag bingle-tests:ping --test ping_registered_node

# Set explicit filter to the ping test function
PING_FILTER="testnet_send_ping_to_registered_node"

# Decide which pingable NAT modes to exercise
if [ "$NAT_MODE" = "All" ] || [ "$NAT_MODE" = "all" ]; then
  PING_MODES=("Direct" "Full" "Restricted")
else
  PING_MODES=("$PING_INIT_MODE")
fi

PING_OUT_BASE="$PWD/tmp/test_out/test_results_ping"
PING_ANY_FAIL=0
FIRST_MODE=1

for MODE in "${PING_MODES[@]}"; do
  # Restart pingable for subsequent modes
  if [ $FIRST_MODE -eq 0 ]; then
    echo "Restarting bingle_pingable with NAT_MODE=$MODE..."
    docker stop bingle_pingable >/dev/null 2>&1 || true
    # Wait for container to be fully stopped and removed
    timeout=10
    elapsed=0
    while docker ps -a --format '{{.Names}}' | grep -q "^bingle_pingable$" && [ $elapsed -lt $timeout ]; do
      sleep 0.5
      elapsed=$((elapsed + 1))
    done
    # Force remove if still exists
    docker rm -f bingle_pingable >/dev/null 2>&1 || true
    # Increment IP address for new container
    PINGABLE_IP_SUFFIX=$((PINGABLE_IP_SUFFIX + 1))
    echo "Using IP address 172.18.0.$PINGABLE_IP_SUFFIX for bingle_pingable restart"
    PING_SENT="pingable_${MODE}_${PINGABLE_PORT}.sentinel"
    echo "Removing $SENT_DIR/$PING_SENT"
    rm -f "$SENT_DIR/$PING_SENT"
    docker run --platform linux/arm64 -d --rm \
      --name bingle_pingable \
      --network bingle_testnet \
      --ip "172.18.0.$PINGABLE_IP_SUFFIX" \
      --cap-add NET_ADMIN \
      -e PASSPHRASE="$PINGABLE_PASSPHRASE" \
      -e PORT=$PINGABLE_PORT \
      -e HANDLE=$PINGABLE_USER \
      -e NAT_MODE="$MODE" \
      -e SENTINEL_FILE="/sentinels/$PING_SENT" \
      -v "$PWD/tmp/sentinels":/sentinels \
      -v "$PWD/tmp/stunservers.txt":/app/stunservers.txt:ro \
      "bingle:local"
    if [ $? -ne 0 ]; then
      echo "ERROR: Failed to start bingle_pingable container for mode $MODE" >&2
      PING_ANY_FAIL=1
      continue
    fi
    # Wait for per-mode pingable listening sentinel
    echo "Waiting for $SENT_DIR/$PING_SENT"
    if ! wait_for_file "$SENT_DIR/$PING_SENT" 240; then
      echo "ERROR: Pingable did not signal listening for mode $MODE within timeout" >&2
      PING_ANY_FAIL=1
      continue
    fi
  fi

  # Run the ping test with the sender in Direct mode; write per-mode output file inside /out
  OUT_FILE_MODE="/out/$(basename "${PING_OUT_BASE}_${MODE}.out")"
  docker run --platform linux/arm64 --rm \
    --name bingle_test_runner_ping \
    --network bingle_testnet \
    --cap-add NET_ADMIN \
    -e NAT_MODE="Direct" \
    -e TEST_FILTER="$PING_FILTER" \
    -e TESTNET_USER="$TESTNET_USER" \
    -e TESTNET_PASSPHRASE="$TESTNET_PASSPHRASE" \
    -e PINGABLE_ADDRESS="$PINGABLE_ADDRESS" \
    -e OUT_FILE="$OUT_FILE_MODE" \
    -v "$PWD/tmp/test_out":/out \
    -v "$PWD/tmp/stunservers.txt":/app/stunservers.txt:ro \
    "bingle-tests:ping"
  rc=$?
  if [ $rc -ne 0 ]; then
    echo "ERROR: Ping test container failed in mode $MODE with exit code $rc" >&2
    PING_ANY_FAIL=1
  fi
  # Append a clear per-mode result line to the host file
  host_file="${PING_OUT_BASE}_${MODE}.out"
  if [ $rc -eq 0 ]; then
    echo "[runner][$MODE] Test PASSED" >> "$host_file"
  else
    echo "[runner][$MODE] Test FAILED with exit code $rc" >> "$host_file"
  fi

  FIRST_MODE=0
  # Ensure the runner container is not lingering
  docker stop bingle_test_runner_ping >/dev/null 2>&1 || true

done

# Combine all per-mode ping outputs into the canonical PING_OUT file
: > "$PING_OUT"
for MODE in "${PING_MODES[@]}"; do
  host_file="${PING_OUT_BASE}_${MODE}.out"
  if [ -f "$host_file" ]; then
    echo "" >> "$PING_OUT"
    echo "==== Ping mode $MODE ====" >> "$PING_OUT"
    cat "$host_file" >> "$PING_OUT"
  fi
done

# Set overall PING_RC for later summary
if [ $PING_ANY_FAIL -ne 0 ]; then
  PING_RC=1
else
  PING_RC=0
fi

# ---------------------------
# Extract and consolidate results
# ---------------------------
echo ""
echo "================ Consolidated Test Results ================"

# Show individual results from the main run
if [[ -f "$MAIN_OUT" ]]; then
  echo "-- Main run (per-mode results) --"
  grep -E '^\[runner\]\[(Direct|Full|Restricted)\] Test ' "$MAIN_OUT" || echo "(no per-mode result lines found)"
  echo "-- Main run (summary) --"
  grep -E '^\[runner\]\[summary\]' "$MAIN_OUT" || echo "(no summary lines found)"
else
  echo "[WARN] Main results file not found: $MAIN_OUT"
fi

# Show results from the ping run
if [[ -f "$PING_OUT" ]]; then
  echo "-- Ping run (per-mode results) --"
  grep -E '^\[runner\]\[(Direct|Full|Restricted)\] Test ' "$PING_OUT" || echo "(no per-mode result lines found)"
else
  echo "[WARN] Ping results file not found: $PING_OUT"
fi

# Determine statuses
MAIN_STATUS="UNKNOWN"
PING_STATUS="UNKNOWN"

if [[ -f "$MAIN_OUT" ]]; then
  if grep -Eq '^\[runner\]\[summary\].*FAILED' "$MAIN_OUT"; then
    MAIN_STATUS="FAIL"
  elif grep -Eq '^\[runner\]\[summary\].*PASSED' "$MAIN_OUT"; then
    # If any PASSED summaries found and no FAILED, consider PASS
    MAIN_STATUS="PASS"
  else
    # Fall back to exit code
    if [[ ${MAIN_RC:-1} -eq 0 ]]; then MAIN_STATUS="PASS"; else MAIN_STATUS="FAIL"; fi
  fi
else
  if [[ ${MAIN_RC:-1} -eq 0 ]]; then MAIN_STATUS="PASS"; else MAIN_STATUS="FAIL"; fi
fi

if [[ -f "$PING_OUT" ]]; then
  # If any mode failed, overall ping run is FAIL
  if grep -Eq '^\[runner\]\[(Direct|Full|Restricted)\] Test FAILED' "$PING_OUT"; then
    PING_STATUS="FAIL"
  # Otherwise, if at least one mode passed and none failed, it's a PASS
  elif grep -Eq '^\[runner\]\[(Direct|Full|Restricted)\] Test PASSED' "$PING_OUT"; then
    PING_STATUS="PASS"
  else
    # Fall back to aggregated RC from per-mode runs
    if [[ ${PING_RC:-1} -eq 0 ]]; then PING_STATUS="PASS"; else PING_STATUS="FAIL"; fi
  fi
else
  if [[ ${PING_RC:-1} -eq 0 ]]; then PING_STATUS="PASS"; else PING_STATUS="FAIL"; fi
fi

# Extract and display timing information
echo "-- Timing Summary --"
if [[ -f "$MAIN_OUT" ]]; then
  echo "Main run timings (NAT_MODE=$NAT_MODE):"
  # Prefix each timing line with the NAT mode used by the main test container
  grep "TIMING:" "$MAIN_OUT" | sed "s/^/  [NAT=$NAT_MODE] /" || echo "  (no timing info found)"
fi

# For ping run, show timings per NAT mode exercised (if any)
echo "Ping run timings:"
if [[ -n "${PING_MODES[*]:-}" ]]; then
  any_timing=0
  for MODE in "${PING_MODES[@]}"; do
    host_file="${PING_OUT_BASE}_${MODE}.out"
    if [[ -f "$host_file" ]]; then
      # Prefix per-mode timing lines with the NAT mode
      if grep -q "TIMING:" "$host_file"; then
        grep "TIMING:" "$host_file" | sed "s/^/  [NAT=$MODE] /"
        any_timing=1
      fi
    fi
  done
  if [[ $any_timing -eq 0 ]]; then
    echo "  (no timing info found)"
  fi
else
  if [[ -f "$PING_OUT" ]]; then
    # Fallback: prefix timings found in combined file without per-mode context
    grep "TIMING:" "$PING_OUT" | sed 's/^/  /' || echo "  (no timing info found)"
  else
    echo "  (no timing info found)"
  fi
fi

echo "-- Overall --"
echo "Main run: $MAIN_STATUS"
echo "Ping run: $PING_STATUS"

if [[ "$MAIN_STATUS" == "PASS" && "$PING_STATUS" == "PASS" ]]; then
  echo "OVERALL RESULT: PASS"
  exit 0
else
  echo "OVERALL RESULT: FAIL"
  # Prefer returning the first non-zero original RC if available
  if [[ ${MAIN_RC:-0} -ne 0 ]]; then exit ${MAIN_RC:-1}; fi
  if [[ ${PING_RC:-0} -ne 0 ]]; then exit ${PING_RC:-1}; fi
  exit 1
fi

