// Grouped CLI tests
#[path = "app_support.rs"]
pub mod app_support;
#[path = "chat_args.rs"]
pub mod chat_args;
#[path = "chat_receive.rs"]
pub mod chat_receive;
#[path = "chat_register.rs"]
pub mod chat_register;
#[path = "chat_repl.rs"]
pub mod chat_repl;
#[path = "chat_send.rs"]
pub mod chat_send;
#[path = "chat_state.rs"]
pub mod chat_state;
#[path = "echo_mode.rs"]
pub mod echo_mode;
#[path = "run_args.rs"]
pub mod run_args;
#[path = "shutdown.rs"]
pub mod shutdown;
#[path = "version_help.rs"]
pub mod version_help;
